### ISSUE TITLE
How can I introspect a prismic graphql endpoint for codegen with apollo?

### ISSUE THREAD

**Issue by martaver** [prismicio/apollo-link-prismic#19]
I have a graphql endpoint at https://beaufort-asia.prismic.io/graphql.

I have installed apollo CLI (yarn global add apollo).

I have `apollo.config.js` with:
```
module.exports = {
    client: {
        service: {
            name: 'beaufort-asia',
            url: 'https://beaufort-asia.prismic.io/graphql',
        }
    }
}
```

I run apollo client:check and it fails:

```
Checking client compatibility with service
 ›   Error: Error initializing Apollo GraphQL project "beaufort-asia": Error: Error in 
 ›   "Loading schema for beaufort-asia": Error: Apollo tried to introspect a running GraphQL 
 ›   service at https://beaufort-asia.prismic.io/graphql
 ›   It expected a JSON schema introspection result, but got an HTML response instead.
 ›   You may need to add headers to your request or adjust your endpoint url.
 ›   -----------------------------
 ›   For more information, please refer to: https://go.apollo.dev/t/config 
 ›
 ›   The following error occurred:
 ›   -----------------------------
 ›   Unexpected token < in JSON at position 0
```

How can I introspect the graphql endpoint, so that I can codegen types and get IDE tooling for it?

**Comment by angeloashmore** [comment]
Hi @martaver, apologies for such a late reply. Prismic's GraphQL API uses GET requests rather than the more typical POST requests used in most GraphQL APIs.

As a result, Apollo's CLI for generating types is not compatible, at least not out-of-the-box.

If you would like to get the schema of your GraphQL API for your repository, see this comment in another issue: https://github.com/prismicio/apollo-link-prismic/issues/2#issuecomment-1069804614
