### ISSUE TITLE
Cache issue with prismic-ref

### ISSUE THREAD

**Issue by mossypaul** [prismicio/apollo-link-prismic#39]
Hi,

I might be doing something wrong but I'm having problems with stale data.

Does it take into account the `prismic-ref` when caching responses? Or is there something I'm missing to make it do this? I've tried setting the `fetchPolicy` on `useQuery` to `'no-cache'` but it's still using stale data from the cache.

Cheers,
Paul

**Comment by code-vagabond** [comment]
Hi @mossypaul,

have you found any solutions for this yet ? 

I struggled with this for a while now, the new release (1.1.0) which uses @prismicio/client doesn't seem to help.

Best regards,

Linh

**Comment by leffot** [comment]
Hey @code-vagabond,

I'm not @mossypaul, but I've tried 1.1.0, too, and still have the issue. I also tried dropping this dep entirely and creating an HttpLink as outlined [here](https://github.com/prismicio/prismic-client/issues/202#issue-1077360035), but the issue persists. I imagine there must be a bug somewhere in the `graphqlFetch` implementation of the latest `@prismicio/client`.

There's [a thread](https://community.prismic.io/t/graphql-cache-issue/8997) on Prismic's site tracking this issue. No solutions yet, but hopefully something soon, as this bug is a real headache.

**Comment by mossypaul** [comment]
Hey @code-vagabond, nope, no solution yet. Although as @leffot mentioned there's a thread with them, and hopefully they are looking into it. Not being able to get the latest updates from a CMS is a bit of a problem!

**Comment by code-vagabond** [comment]
Hi @leffot  and @mossypaul,

Yes indeed, I also tried to add the `Prismic-ref` manually first via the provided `createPrismicLink` method and then via the `context` variable inside the `QueryOptions`. Both methods did not work. 

Not having latest update from CMS is indeed a life-or-death issue for many businesses (e.g news, e-commerce) let alone don't have any update at all. 

In the current state, you would have to guide the user to disable cache in order for the app to work with update-to-date content. I am considering to switch back to HTTP in worse case, hope this gets resolved soon.

**Comment by angeloashmore** [comment]
Hey @mossypaul, @code-vagabond, @leffot,

Could you try the latest alpha version, `v1.1.1-alpha.0` and let me know if it fixes the issue?

This version adds the `Prismic-ref` value as a `ref` URL parameter to the query URL. This should cache-bust queries when new content is published in Prismic. The GraphQL API will only read the header, but caches typically only compare the URL. Since the URL does not change between queries, even if the ref changed, a cached response could be returned. This circumvents that limitation.

**Comment by code-vagabond** [comment]
Hi @angeloashmore,

After disabled cache that was generated by the older version of the package, your fix worked wonderfully for me, thank you for looking into this!

**Comment by mossypaul** [comment]
Hey @angeloashmore, yep that seems to fix it! Thanks

(and yeah, that makes sense as a solution, that's what we were thinking)

**Comment by leffot** [comment]
Thanks, @angeloashmore!

**Comment by angeloashmore** [comment]
Thanks for testing so quickly!

**The fix is published in the latest version, `v1.1.1`. 🎉**

If you find new cache-related issues in the future, please comment here (or in a new issue) and I will follow up.

**Comment by mossypaul** [comment]
@angeloashmore hmm... I got it working on our website, but when I try using in our react native app I get the error `Error: An invalid Prismic Rest API V2 endpoint was provided: https://mossyearth.cdn.prismic.io/graphql`, if I put the config as: 
`link: createPrismicLink({
        uri: 'https://mossyearth.cdn.prismic.io/graphql',
        accessToken: apiKey,
    }),`

and a general error from the useQuery if providing just the repository name of `mossyearth`, which if I print out the generated url is `https://mossyearth.cdn.prismic.io/api/v2`

Any thoughts?

**Comment by angeloashmore** [comment]
@mossypaul This might happen because React Native does not include a full implementation of the `URL` interface.

`@prismicio/client` uses `URL` heavily to build the REST and GraphQL URLs. The "invalid Prismic Rest API V2" error is coming from `@prismicio/client`'s [`getRepositoryName()`](https://github.com/prismicio/prismic-client/blob/27bf0ee5633cf85c6221918fea089d909705c1ed/src/getRepositoryName.ts) function. If you look at its code, you'll see that there's nothing in there that would cause that issue with the `uri` you gave, unless `URL` isn't fully implemented.

You can see here that RN's `URL` implementation throws errors for most of its methods: https://github.com/facebook/react-native/blob/8c0c860e38f57e18296f689e47dfb4a54088c260/Libraries/Blob/URL.js#L115-L222

Could you try the steps described here: https://prismic.io/docs/technical-reference/prismicio-client#installation-with-react-native

I will add a note to this package's README if this fixes your RN issue.

**Comment by mossypaul** [comment]
@angeloashmore ahh, I wish I had asked sooner!

This wasn't a problem previously, but that looks like it's fixed it, although I had to go for option two from https://www.npmjs.com/package/react-native-url-polyfill (Using expo and App.tsx)

**Comment by angeloashmore** [comment]
Ah, good to know! Thanks for testing it. I'll add a note to the README with a note to try Option 2 if the easy method (Option 1) doesn't work.

**Edit**: Updated here: https://github.com/prismicio/apollo-link-prismic#installation-with-react-native

**Comment by mossypaul** [comment]
Thanks for your help @angeloashmore
