### ISSUE TITLE
Allow to specify preview ref

### ISSUE THREAD

**Issue by igorlesnenko** [prismicio/apollo-link-prismic#4]
Allow to specify preview ref

**Comment by mitevs-mms** [comment]
I created a PR for this https://github.com/prismicio/apollo-link-prismic/pull/5

**Comment by Mk-Etlinger** [comment]
@mitevs-mms Awesome! Thanks for this.

I'm still having some trouble getting it to work, however. Do you have a working example repo somewhere that I could take a look at?

~Here's what I'm currently trying.~
DON'T DO THIS(since fixed):

```javascript
// Setup client above with PrismicLink

const previewRef = req.cookies['io.prismic.preview']

const response = await client.query({
      query: query,
      context: {
        headers: {
          'Prismic-ref': previewRef,
        }
      }
    })
```
**edit**
Talked to the Prismic team and they said you're not supposed to pass in the entire preview cookie. Only the cookie with the value of preview, which looks like `https://my-repo.prismic.io/previews/OUOIJKJNNKJCNKHI?websitePreviewId=aOInNNKJKJUIGGG`

Here's a simplified version of how I fixed this. My error was sending the entire cookie, not just the Preview Link

```javascript
// Setup client above with PrismicLink

const cookies = request.cookies // For Node/Express or client side you can parse document.cookies

const prismicPreviewCookies = cookies['io.prismic.preview']
const repoCookie = prismicPreviewCookies['my-repo.prismic.io']
const previewRefURL = repoCookie['preview']
let queryContext

if (previewRefURL) {
  queryContext = {
      headers: {
        'Prismic-ref': previewRefURL,
      }
   }
}

const response = await client.query({
      query: query,
      context: queryContext,
    })
```

~Unfortunately, it still doesn't work.~
Fixed with the above code.


Thanks!

**Comment by Duaner** [comment]
Closing this one. Fixed by https://github.com/prismicio/apollo-link-prismic/pull/5
